
Spring:
    application:
        name=springbootmybatisstart:
    datasource:
        url: jdbc:mysql://localhost:3306/logixswift
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
